### PR TITLE
support for Basic authentication of Kong admin API

### PR DESCRIPTION
**Pull request by miso-m**

### CODE REVIEW

**Comment by kevinpgrant** [comment]
If promoting the use of basic auth credentials on the Kong backend, some users could fail to realise that they also should use a secure (https or TLS) connection at the same time. It probably makes a lot of sense to also encourage the use of TLS/https, in a README or tooltip perhaps?

**Comment by miso-m** [comment]
good point, I changed tooltips

**Comment by ntimo** [comment]
Any news when this might get merged?

**Comment by miloszwatroba** [comment]
@pantsel Any plans to merge this PR?

**Pull request merged**
