### PR TITLE
missing ssl mode

### PR DESCRIPTION
**Pull request by balexandre**
missing the ssl mode in the postres options upon connection

### CODE REVIEW

**Comment by pantsel** [comment]
@balexandre , did you mean

<pre>  
{
    database: dbName,
    password: password,
    port: dbPort,
    ssl: ssl <-----------
}</pre>

**Comment by balexandre** [comment]
@pantsel in a json object if the property is the same as the object holding the value, you can simplify with just the object property

for example:

```javascript
const options = {
    database,
    password,
    port,
    ssl
};
```

is the same as 

```javascript
const options = {
    database: database,
    password: password,
    port: port,
    ssl: ssl
};
```

that's actually an ESLint rule called [object-shorthand](https://eslint.org/docs/rules/object-shorthand).

**Comment by pantsel** [comment]
In ES6. Konga is ES5 all the way so it's inconsistent with the current coding style,

Apart from that, have you tested it yourself (travis checks aside)?

**Comment by balexandre** [comment]
@pantsel I'm running it as we speak ... err write.

fell free to test yourself, or change to the format you prefer, but that option is missing and `ssl: true` is needed when using Heroku database for example.

I'm trying to debug the app for 2 days now, found some issues, but that one was a big one and I thought it would be best to create a PR.

**Comment by pantsel** [comment]
@balexandre ,

the only reason I asked you is because lately I'm up to my head with work and iIdon't have time to actually test or do anything Konga related.

Apart form that, it comes without saying that your contribution is really appreciated!

Feel free to create more PRs if you see fit or open some issues about the things you stumbled upon.

Cheers!

**Comment by balexandre** [comment]
just so you see connecting without issues

[](https://s6.postimg.org/rxdgpnnup/screenshot_150.png)

**Pull request merged**
