### PR TITLE
Changed Dockerfile so that the application doesn't run as root

### PR DESCRIPTION
**Pull request by HansK-p**
Ideally Konga should not run as root inside the container. This change makes it so that Konga runs with the uid/guid of the node user.

The change has only been lightly tested.

### CODE REVIEW

**Comment by pantsel** [comment]
@HansK-p , thanks a bunch for the contrib.

Can you please change the pull req branch to [next](https://github.com/pantsel/konga/tree/next) so I can merge and run some tests?

Cheers!

**Comment by HansK-p** [comment]
Done + fingers crossed.

**Comment by HansK-p** [comment]
This is a breaking change in that it will most probably create issues for users who are upgrading from an earlier version and are using the local database. I haven't tested, but i assume Konga will not be able to modify locate files owned by root after it has been updated - if this patch is applied.

It is still a good idea to not run Konga as root due to security concerns, so it would be good to make this change at some time or write instructions as to how Konga can be run with a custom user id.

So I won't close my pull request. I'll just understand it if the pull request is rejected.

**Comment by HansK-p** [comment]
@pantsel I adjusted Dockerfile so that a user account "konga" is added and it should be possible to run Konga in Docker as this user. The default is still that Konga will run as root - to keep backward compatibility.
This is (close to) the same as I do when running Konga in K8s and it seems to work well.

**Pull request merged**
